# shellcheck shell=bash
export RUSH_CONFIG="${HOME}/.config/rush/config"
export RUSH_ROOT="${HOME}/.local/share/rush"
export HOMELAB_VHMOST_BASH_CONFIGURED=1

ll() {
  ls -lh "$@"
}

config_update() {
  (
    set -euo pipefail
    cd /opt/config/homelab-vmhost
    git pull
    make
  )
}

# bitwarden unlock
bwu() {
  BW_SESSION="$(bw unlock --raw)"
  export BW_SESSION
}

# bitwarden lock
bwl() {
  bw lock
  BW_SESSION=
}
