[DEFAULT]
DefaultZone=drop
MinimalMark=100
CleanupOnExit=yes
Lockdown=no
IPv6_rpfilter=yes
IndividualCalls=no
LogDenied=off
AutomaticHelpers=no
FlushingOnReload=no
AllowZoneDrifting=no
MaxConnections=1000
TCPHalfOpenLimit=128
IPv6AutoTunnel=yes
