# this is the init preseed that got dumped after answering all questions interactively
config: {}
networks:
  - config:
      ipv4.address: auto
      ipv6.address: auto
    description: ""
    name: incusbr0
    type: ""
    project: default
storage_pools:
  - config:
      # [tag:incus-pool-config]
      # incus defaults storage to /var/...
      # however my debian reserves only a small amount of space there.
      # /srv is more appropriate
      source: /srv/incus
    description: ""
    name: default
    driver: dir
storage_volumes: []
profiles:
  - config: {}
    description: ""
    devices:
      eth0:
        name: eth0
        network: incusbr0
        type: nic
      root:
        path: /
        pool: default
        type: disk
    name: default
    project: default
projects: []
cluster: null
